name: Release

on:
  release:
    types: published

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-15] # Windows is not supported (not working with devenv/nix setup)
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - uses: cachix/cachix-action@v15
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv

    - name: Create binding distribution
      run: devenv shell -- bash -c "make release-uniffi-bindings VERSION=${{ github.ref_name }}"

    - name: Set ARCH environment variable
      run: echo "ARCH=$(uname -m)" >> $GITHUB_ENV

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: ./dist/dnssec-prover-${{ github.ref_name }}-${{ env.ARCH }}.tar.gz
